# Generated by Django 5.0.4 on 2024-04-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chapte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapte',
            new_name='Chapter',
        ),
    ]
