# Generated by Django 5.0.4 on 2024-04-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_chapte_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='category',
            new_name='course',
        ),
    ]
