# Generated by Django 5.0.4 on 2024-05-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
