# Generated by Django 5.0.4 on 2024-05-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='teacehr',
            new_name='teacher',
        ),
    ]
