# Generated by Django 5.0.4 on 2024-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_studentassignment_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
    ]
