# Generated by Django 5.0.4 on 2024-05-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz_coursequiz_quizquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='title',
        ),
    ]
