# Generated by Django 5.0.4 on 2024-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_quizquestions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='right_an',
        ),
    ]
