# Generated by Django 5.0.4 on 2024-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_quizquestions_right_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
