# Generated by Django 5.0.4 on 2024-05-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_coursequiz_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '14. Attempted Questions'},
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
